[project]
name = "doc-ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "pydantic>=2.10.5",
    "pydantic-settings>=2.7.1",
    "loguru>=0.7.3",
    "markitdown[all]>=0.0.1a2",
    "openai>=1.59.7",
    "requests>=2.32.3",
    "minio>=7.2.12",
    "oss2>=2.19.1",
    "cos-python-sdk-v5>=1.9.31",
    "python-multipart>=0.0.21",
    "tenacity>=9.0.0",
]

[build-system]
requires = ["hatchling>=1.24.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["app"]
